apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  labels:
    mydecisive.ai/hub-name: mdaihub-pii
  name: gateway
  namespace: mdai
spec:
  managementState: managed
  image: otel/opentelemetry-collector-contrib:0.127.0
  replicas: 1
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  envFrom:
    - configMapRef:
        name: mdaihub-pii-variables
  config:
    receivers:
      fluentforward:
        endpoint: "${env:MY_POD_IP}:8006"

    extensions:
      health_check:
        endpoint: "${env:MY_POD_IP}:13133"

    processors:
      memory_limiter:
        check_interval: 23s
        limit_percentage: 75
        spike_limit_percentage: 15

      batch:
        send_batch_size: 1000
        send_batch_max_size: 10000
        timeout: 13s

    attributes/redact_pii_fields:
      actions:
        - key: email
          action: delete
        - key: phone
          action: delete
        - key: ssn
          action: delete
        - key: address
          action: delete

    transform/scrub_pii_fields:
      error_mode: propagate
      log_statements:
        - context: log
          statements:
            # Redact credit card numbers (keep last 4 digits)
            - ${env:CC_REPLACE_FN}

            # Redact email addresses (keep first 3 characters of username)
            - replace_pattern(attributes["email"], ${env:EMAIL_REGEX}, ${env:EMAIL_TEMPLATE})

            # Redact phone numbers (keep last 4 digits)
            - replace_pattern(attributes["phone"], ${env:PHONE_REGEX}, ${env:PHONE_TEMPLATE})

            # Redact address (keep first 4 digits)
            - replace_pattern(attributes["billing_address"], ${env:ADDRESS_REGEX}, ${env:ADDRESS_TEMPLATE})

            # Redact SSN (keep last 4 digits)
            - replace_pattern(attributes["ssn"], ${env:SSN_REGEX}, ${env:SSN_TEMPLATE})

            # Redact Name (fully redact name)
            - replace_pattern(attributes["name"], ${env:NAME_REGEX}, ${env:NAME_TEMPLATE})

    attributes/hash_pii_fields:
      actions:
        - key: email
          action: hash
        - key: phone
          action: hash
        - key: ssn
          action: hash
        - key: address
          action: hash

    exporters:
      # debug: {}

      # debug/redact_pii_fields:
      debug/hash_pii_fields:
      # debug/scrub_pii_fields:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200

    service:
      telemetry:
        resource:
          mdai-logstream: collector
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: "0.0.0.0"
                    port: 8888
      extensions: [health_check]
      pipelines:
        logs/customer_pipeline:
          receivers: [fluentforward]
          processors: [
            # attributes/redact_pii_fields,
            attributes/hash_pii_fields,
            # transform/scrub_pii_fields,
            memory_limiter,
            batch,
          ]
          exporters: [
            # debug/redact_pii_fields
            debug/hash_pii_fields
            # debug/scrub_pii_fields
          ]
