apiVersion: hub.mydecisive.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-pii
  namespace: mdai
spec:
  variables:
    - key: fields_to_redact
      type: manual
      serializeAs:
        - name: "FIELDS_TO_REDACT"
          transformers:
            - type: join
              join:
                delimiter: "|"
      dataType: set
      storageType: "mdai-valkey"

    - key: fields_to_hash
      type: manual
      serializeAs:
        - name: "FIELDS_TO_HASH"
          transformers:
            - type: join
              join:
                delimiter: "|"
      dataType: set
      storageType: "mdai-valkey"

    # regex patterns

    - key: email_regex
      type: manual
      serializeAs:
        - name: "EMAIL_REGEX"
      dataType: string
      storageType: "mdai-valkey"

    - key: cc_regex
      type: manual
      serializeAs:
        - name: "CC_REGEX"
      dataType: string
      storageType: "mdai-valkey"

    - key: phone_regex
      type: manual
      serializeAs:
        - name: "PHONE_REGEX"
      dataType: string
      storageType: "mdai-valkey"

    - key: address_regex
      type: manual
      serializeAs:
        - name: "ADDRESS_REGEX"
      dataType: string
      storageType: "mdai-valkey"

    - key: ssn_regex
      type: manual
      serializeAs:
        - name: "SSN_REGEX"
      dataType: string
      storageType: "mdai-valkey"

    - key: name_regex
      type: manual
      serializeAs:
        - name: "NAME_REGEX"
      dataType: string
      storageType: "mdai-valkey"

    # replace templates

    - key: email_template
      type: manual
      serializeAs:
        - name: "EMAIL_TEMPLATE"
      dataType: string
      storageType: "mdai-valkey"

    - key: cc_template
      type: manual
      serializeAs:
        - name: "CC_TEMPLATE"
      dataType: string
      storageType: "mdai-valkey"

    - key: phone_template
      type: manual
      serializeAs:
        - name: "PHONE_TEMPLATE"
      dataType: string
      storageType: "mdai-valkey"

    - key: address_template
      type: manual
      serializeAs:
        - name: "ADDRESS_TEMPLATE"
      dataType: string
      storageType: "mdai-valkey"

    - key: ssn_template
      type: manual
      serializeAs:
        - name: "SSN_TEMPLATE"
      dataType: string
      storageType: "mdai-valkey"

    - key: name_template
      type: manual
      serializeAs:
        - name: "NAME_TEMPLATE"
      dataType: string
      storageType: "mdai-valkey"
