apiVersion: hub.mydecisive.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-ia
  namespace: mdai
spec:
  variables:
    - key: service_list
      serializeAs:
        - name: "SERVICE_LIST_REGEX"
          transformers:
            - type: join
              join:
                delimiter: "|"
      dataType: set
      storageType: "mdai-valkey"
    - key: alerting_data_type
      dataType: string
      serializeAs:
        - name: "ALERTING_DATA_TYPE"
    - key: alerting_triggered
      dataType: boolean
      serializeAs:
        - name: "ALERT_TRIGGERED"

    # Example: key "checkout-service" -> value "Checkout service is above expected error rate"
    - key: alert_message_map
      type: manual
      dataType: map
      storageType: mdai-valkey
      serializeAs:
        - name: "ALERT_MESSAGE_MAP"

    # Computed key: the current lookup key (e.g., mdai_service)
    - key: alert_message_key
      type: computed
      dataType: string
      storageType: mdai-valkey
      serializeAs:
        - name: "ALERT_MESSAGE_KEY"

    # Meta lookup: resolves to alert_message_map[alert_message_key]
    - key: alert_message
      type: meta
      dataType: metaHashSet
      storageType: mdai-valkey
      variableRefs:
        - alert_message_key
        - alert_message_map
      serializeAs:
        - name: ALERT_MESSAGE

  prometheusAlerts:
    - name: anomalous_error_rate
      # two part query
      # first part checks if the error rate is a specific multiplier of the normal error rate over the last hour
      # second part ensures there is at least an hour's worth of data to check against, to prevent false-positives
      # expr: 'sum(increase(error_logs_by_service_total[5m])) by (mdai_service) > 2 * sum(avg_over_time(increase(error_logs_by_service_total[5m])[1h:])) by (mdai_service) and (sum by (mdai_service) (error_logs_by_service_total offset 1h))'
      # Replace the above line with the following to test lower thresholds
      expr: 'sum(increase(error_logs_by_service_total[5m])) by (mdai_service) > 0.1 * sum(avg_over_time(increase(error_logs_by_service_total[5m])[1h:])) by (mdai_service)'
      severity: warning
      for: 3m
      keep_firing_for: 3m
    
    # - name: unmasked_cc_detected
    #   expr: 'sum(increase(cc_unmasked_logs_total[5m])) by (mdai_service) > 0'
    #   severity: critical
    #   for: 1m
    #   keep_firing_for: 10m

  rules:
    - name: anomalous_error_rate
      when:
        alertName: anomalous_error_rate
        status: firing
      then:
        - callWebhook:
            url:
              valueFrom:
                # Read the URL from a Secret (recommended)
                secretKeyRef: {name: slack-webhook-secret, key: url }
            templateRef: slackAlertTemplate
            templateValues:
              labels_val_ref_primary: mdai_service
              message: "${variables:alert_message}"
              link_url: http://localhost:9090/alerts
              link_text: See alert in Prometheus

    - name: anomalous_error_rate_firing
      when:
        alertName: anomalous_error_rate
        status: firing
      then:
        - addToSet:
            set: service_list
            value: ${trigger:payload.labels.mdai_service}
        - setVariable:
            scalar: alert_message_key
            value: ${trigger:payload.labels.mdai_service}

    - name: anomalous_error_rate_resolved
      when:
        alertName: anomalous_error_rate
        status: resolved
      then:
        - removeFromSet:
            set: service_list
            value: ${trigger:payload.labels.mdai_service}        

    # - name: unmasked_cc_detected
    #   when:
    #     alertName: unmasked_cc_detected
    #     status: firing
    #   then:
    #     - callWebhook:
    #         url:
    #           valueFrom:
    #             secretKeyRef: { name: slack-webhook-secret, key: url }
    #         templateRef: slackAlertTemplate
    #         templateValues:
    #           labels_val_ref_primary: mdai_service
    #           message: Unmasked credit card data detected in logs (cc attribute). Investigate immediately.
    #           link_text: See alert in Prometheus
    #           link_url: http://localhost:9090/alerts
              
        # GH integration example below      
        # - callWebhook:
        #   url:
        #     valueFrom:
        #       secretKeyRef:
        #         name: github-webhook-url
        #         key: GITHUB_WEBHOOK_URL
        #   method: POST
        #   templateRef: jsonTemplate
        #   payloadTemplate:
        #     value: |-
        #       {
        #         "ref": "${template:ref:-main}",
        #         "inputs": {
        #           "env": "${template:env:-prod}",
        #           "build_id": "${trigger:id}"
        #         }
        #       }
        #   templateValues:
        #     ref: main
        #     env: uat
        #   headersFrom:
        #     Authorization:
        #       secretKeyRef:
        #         name: github-token
        #         key: authorization
        #   headers:
        #     Accept: application/vnd.github+json
        #     X-GitHub-Api-Version: "2022-11-28"
        #     Content-Type: application/json