apiVersion: v1
kind: ConfigMap
metadata:
  name: mdai-logger-settings
  namespace: synthetics
data:
  # Common
  COMMON_LOG_MESSAGE: "The algorithm successfully executed, triggering neural pathways and producing a burst of optimized data streams."

  # Base logger (formerly mdai-logger)
  BASE_LOG_MIN_INTERVAL: "1"
  BASE_LOG_MAX_INTERVAL: "5"
  BASE_LOG_MIN_COUNT: "1"
  BASE_LOG_MAX_COUNT: "25"
  BASE_SERVICE_COUNT: "50"

  # Noisy (formerly mdai-logger-noisy)
  NOISY_LOG_MIN_INTERVAL: "20"
  NOISY_LOG_MAX_INTERVAL: "25"
  NOISY_LOG_MIN_COUNT: "500"
  NOISY_LOG_MAX_COUNT: "1000"
  NOISY_SERVICE_NAME: "service1234"

  # Xtra noisy (formerly mdai-logger-xnoisy)
  X_LOG_MIN_INTERVAL: "20"
  X_LOG_MAX_INTERVAL: "25"
  X_LOG_MIN_COUNT: "500"
  X_LOG_MAX_COUNT: "1000"
  X_NOISY_SERVICE_NAME: "service4321"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdai-logger-bundle
  namespace: synthetics
  labels:
    app.kubernetes.io/name: mdai-logger-bundle
    app.kubernetes.io/part-of: mdai-log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mdai-logger-bundle
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mdai-logger-bundle
        app.kubernetes.io/part-of: mdai-log-generator
    spec:
      containers:
        # === Base logger (was mdai-logger) ===
        - name: mdai-logger
          image: busybox
          resources:
            limits: { memory: "16Mi", cpu: "50m" }
            requests: { memory: "8Mi", cpu: "25m" }
          env:
            - name: LOG_MESSAGE
              valueFrom:
                {
                  configMapKeyRef:
                    { name: mdai-logger-settings, key: COMMON_LOG_MESSAGE },
                }
            - name: LOG_MIN_INTERVAL
              valueFrom:
                {
                  configMapKeyRef:
                    { name: mdai-logger-settings, key: BASE_LOG_MIN_INTERVAL },
                }
            - name: LOG_MAX_INTERVAL
              valueFrom:
                {
                  configMapKeyRef:
                    { name: mdai-logger-settings, key: BASE_LOG_MAX_INTERVAL },
                }
            - name: LOG_MIN_COUNT
              valueFrom:
                {
                  configMapKeyRef:
                    { name: mdai-logger-settings, key: BASE_LOG_MIN_COUNT },
                }
            - name: LOG_MAX_COUNT
              valueFrom:
                {
                  configMapKeyRef:
                    { name: mdai-logger-settings, key: BASE_LOG_MAX_COUNT },
                }
            - name: SERVICE_COUNT
              valueFrom:
                {
                  configMapKeyRef:
                    { name: mdai-logger-settings, key: BASE_SERVICE_COUNT },
                }
          command: ["/bin/sh", "-c"]
          args:
            - |
              LEVELS="ERROR WARNING INFO"
              TEAM_NAMES="C D E F G H I J K L M N O P Q R S T U V W X Y Z"
              TEAM_NAMES_ARRAY=$(echo $TEAM_NAMES | tr ' ' '\n')
              while true; do
                COUNT=$(( (RANDOM % (LOG_MAX_COUNT - LOG_MIN_COUNT + 1)) + LOG_MIN_COUNT ))
                INTERVAL=$(( (RANDOM % (LOG_MAX_INTERVAL - LOG_MIN_INTERVAL + 1)) + LOG_MIN_INTERVAL ))
                for i in $(seq 1 $COUNT); do
                  LOG_LEVEL=$(echo $LEVELS | awk -v idx=$((RANDOM % 3 + 1)) '{print $idx}')
                  RANDOM_NUMBER=$((RANDOM % SERVICE_COUNT))
                  SERVICE_NAME="${RANDOM_NUMBER}"
                  TEAM_NAME=$(echo "$TEAM_NAMES_ARRAY" | awk -v idx=$((RANDOM % 26 + 1)) 'NR == idx {print $0}')
                  echo "$(date -Iseconds) - service${SERVICE_NAME} - team${TEAM_NAME} - us-east-1 - ${LOG_LEVEL} - ${LOG_MESSAGE}"
                done
                sleep $INTERVAL
              done
