apiVersion: hub.mydecisive.ai/v1
kind: MdaiDal
metadata:
  namespace: mdai
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaidal-sample
spec:
  aws:
    region: us-east-1
    credentials:
      secretName: aws-credentials
      accessKeyField: AWS_ACCESS_KEY_ID
      secretKeyField: AWS_SECRET_ACCESS_KEY
  s3:
    bucket: telemetry

  granularity: minutely
  marshaler: json
  usePayloadTs: false
